name: Overlay

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out
      uses: actions/checkout@main

    - name: Prepare the environment
      run: |
        sudo apt -y install git-core git xmlstarlet
        sudo apt update

    - name: Build APK's
      run: |
        cd build
        bash build.sh

    - name: Upload APK
      uses: actions/upload-artifact@v3.0.0
      with:
        path: build/*.apk
        name: Overlays
